### ISSUE TITLE
MultiAreaConditioning.doStuff() missing 1 required positional argument: 'unique_id

### ISSUE THREAD

**Issue by Barmagloth** [Davemane42/ComfyUI_Dave_CustomNode#6]
```
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 177, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 56, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 56, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 56, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 65, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
TypeError: MultiAreaConditioning.doStuff() missing 1 required positional argument: 'unique_id'
```

![Screenshot](https://user-images.githubusercontent.com/5877459/229485207-85e0e6f7-c3d7-45ac-b722-c7a3b7757f1e.jpg)

**Comment by Davemane42** [comment]
ComfyUI need to be up to date
